FROM ubuntu2004base:1.0

ARG user
ARG group
ARG user_uid
ARG user_gid

RUN pip3 install \
    kaleido \
    numba \
    pandas \
    datashader \
    pyarrow \
    fastparquet \
    plotly \
    dash

RUN groupadd -g $user_gid $user
RUN useradd -m -u $user_uid -g $user_gid -s /bin/bash $user && echo "$user:$user" | chpasswd && usermod -aG sudo $user

USER $user:$group
WORKDIR /home/$user

RUN git config --global alias.co checkout
RUN git config --global alias.ci commit
RUN git config --global alias.br branch
RUN git config --global alias.st status
RUN git config --global alias.ch cherry-pick
