FROM ubuntu:20.04

RUN ln -snf /usr/share/zoneinfo/Europe/London /etc/localtime && echo "Europe/London" > /etc/timezone

RUN apt-get update
RUN apt-get install -y build-essential \
    zip \
    ruby \
    sudo \
    ssh \
    sshpass \
    git \
    vim \
    mc \
    python3-pip python3.8-venv python3.8-distutils python3.8-dev \
    python-is-python3 \
    xmlto \
    net-tools \
    wget \
    curl \
    netcat \
    software-properties-common \
    cmake \
    make \
    automake \
    autoconf-archive \
    mtools \
    libtool \
    scons \
    pkgconf \
    ninja-build \
    doxygen \
    texinfo \
    lcov \
    openssl \
    libssl-dev \
    e2fsprogs \
    genext2fs \
    sqlite3 \
    jq \
    ansible \
    acl \
    nfs-common \
    bc \
    iputils-ping \
    rsync \
    libncurses-dev \
    gawk
