FROM ubuntu2004base:1.0

ARG user
ARG group
ARG user_uid
ARG user_gid

RUN groupadd -g $user_gid $user
RUN useradd -m -u $user_uid -g $user_gid -s /bin/bash $user && echo "$user:$user" | chpasswd && usermod -aG sudo $user

USER $user:$group
WORKDIR /home/$user

RUN git config --global alias.co checkout
RUN git config --global alias.ci commit
RUN git config --global alias.br branch
RUN git config --global alias.st status
RUN git config --global alias.ch cherry-pick

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
RUN export NVM_DIR="/home/$user/.nvm"; . "$NVM_DIR/nvm.sh" ; . "$NVM_DIR/bash_completion" ; nvm install 14.17.3
